name: Build CLI

on:
  push:
    paths:
      - cli/**
      - .github/workflows/cli.yaml

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Build a package
    - name: Add cargo deb
      run: cargo install cargo-deb

    - name: Build release
      run: cargo deb
      working-directory: ./cli
    
    - uses: actions/upload-artifact@v3
      with:
        name: orkactl-deb
        path: /home/runner/work/orka/orka/cli/target/debian/*.deb
      